### ISSUE TITLE
Setting Headers 

### ISSUE THREAD

**Issue by jamiejackherer** [clue/php-buzz-react#61]
Hopefully someone can explain, firstly, if we can set headers such as a user agent, secondly, how to do so? I have been trying to manipulate so many ways to add a custom user agent and referrer I have gotten lost in what I have done! I am finding myself trying to implement the same methods over and over.. As an example of I'm looking for, with a Guzzle HTTP client we can do - $client->setUserAgent('Test/123'); - but I am using Clue\React\Socks\Client as SocksClient. Looking at the source code I cannot find a function for this, and also looking at the guzzle source and can see it implemented in there. I am not yet advanced enough to apply this myself, although I will try.. :/ can any one help?

**Comment by jamiejackherer** [comment]
This is the code from Guzzle\HTTP\Client do we think adding this to Clue\React\Socks\Client would set the use agent to default_user_agent()?

`function default_user_agent(RequestInterface $request, array &$options) {

        static $defaultAgent = '';

        if (!$defaultAgent) {
            $defaultAgent = 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36';
        }

        return $defaultAgent;
    }

    function setUserAgent(RequestInterface $request, array &$options) {
        $modify = [];

        if (isset($options['headers'])) {
            if (isset($modify['set_headers'])) {
                $modify['set_headers'] = $options['headers'] + $modify['set_headers'];
            } else {
                $modify['set_headers'] = $options['headers'];
            }
            unset($options['headers']);
        }
        // Add the default user-agent header.
        if (!isset($this->config['headers'])) {
            $this->config['headers'] = ['User-Agent' => default_user_agent()];
        } else {
            // Add the User-Agent header if one was not already set.
            foreach (array_keys($this->config['headers']) as $name) {
                if (strtolower($name) === 'user-agent') {
                    return;
                }
            }
            $this->config['headers']['User-Agent'] = default_user_agent();
        }
    }`

**Comment by clue** [comment]
You can pass any number of headers to any of the HTTP methods on the `Browser` object like this:

```php
$promise = $browser->get($url, array('User-Agent' => 'custom'));
```

You'll have to pass all of your custom headers on each call. Once #7 is in, we'll provide an API to apply default headers for all further requests.

I hope this helps :+1:

**Comment by Chunkford** [comment]
Hi @clue ,
Can you help, please?
I'm trying to change the user-agent as it shows react/alpha in my server logs when scrapping an internal html file for testing purposes.

`xxx.xxx.xxx.xx - tom [18/Jul/2018:09:31:56 -0400] "GET /123.html HTTP/1.0" 200 241 "-" "**React/alpha**"`

But adding a custom user-agent as per your comment above doesn't change it.

Could using your queue or ProxyConnector libraries be causing problems?

`

require __DIR__ . '/vendor/autoload.php';

use \React\EventLoop\Factory as LoopFactory;
use \Clue\React\Buzz\Browser as Browser;
use \Clue\React\Mq\Queue as Queue;
use \Clue\React\HttpProxy\ProxyConnector as ProxyConnector;
use \React\EventLoop\LoopInterface as LoopInterface;
use \React\Socket\Connector as Connector;
use \Psr\Http\Message\ResponseInterface as ResponseInterface;

$loop = LoopFactory::create();

$ip = 'xxx.xx.xx.xxx';
$port= 'xxxxx';
$connectionString = rawurlencode( $ip ) . ':' . rawurlencode( $port );

$proxy = new ProxyConnector( $connectionString, new Connector( $loop ) );

$connector = new Connector( $loop, [ 
	'tcp' => $proxy,
] );

$browser = new Browser( $loop, $connector );

$scraper = new Scraper( $browser, $loop );

$urls = [
	...
	...
	...
];
$timeout = 30;
$concurrencyLimit = 10;

$scraper->scrape( $urls, $timeout, $concurrencyLimit );

$loop->run();

print_r( $scraper->getData() );





class Scraper {

	private $browser;
	private $loop;
	private $scraped = [];

    public function __construct( Browser $browser, LoopInterface $loop ) {
		
        $this->browser = $browser;
		$this->loop = $loop;
    }	
	
    public function scrape( $urls = [], $timeout = 5, $concurrencyLimit = 1 ) {
	
		$queue = $this->initQueue( $concurrencyLimit );

		foreach ( $urls as $url ) {

			$promise = $queue( $url )->then(
				function( ResponseInterface $response ) {
					$this->scraped[] = $this->extractFromHtml( (string) $response->getBody() );
				}
			);
		}
	}
	
	private function extractFromHtml( $html ) {
		...
		...
		...
	}

	public function getData() {
		return $this->scraped;
	}		
	
	protected function initQueue( $concurrencyLimit ) {
		 return new Queue( $concurrencyLimit, null, function ( $url ) {
			   return $this->browser->get( $url, [ 'User-Agent' => 'custom' ] );
		 });
	}

}

`

**Comment by Chunkford** [comment]
@clue I'm so sorry, It works as intended. It was a fault my end

**Comment by clue** [comment]
@Chunkford No worries, thanks for reporting back that this seems to work as expected! :+1:

**Comment by Chunkford** [comment]
It sure does, and here's an extra bit of code to randomly pick a user agent string if anyone finds it useful
I've updated the initQueue function, but I'm sure it can be used else where :)

```
    protected function initQueue( $concurrencyLimit ) {
		
        return new Queue( $concurrencyLimit, null, function ( $url ) {
			
			$userAgents = [
				'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246',
				'Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36',
				'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/601.3.9 (KHTML, like Gecko) Version/9.0.2 Safari/601.3.9',
				'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36',
				'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:15.0) Gecko/20100101 Firefox/15.0.1',
				'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36',
				'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36',
				'Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12 Version/12.16',
				'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
				'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.48 Safari/537.36',
			];
	
            return $this->browser->get( $url, [ 'User-Agent' => $userAgents[array_rand( $userAgents )] ] );
        });
    }
```
