### ISSUE TITLE
Upgrade to new ReactPHP components

### ISSUE THREAD

**Issue by clue** [clue/php-buzz-react#62]
This component uses deprecated SocketClient which has been replaced by Socket. Also, the HttpClient will be merged into the Http component. Both changes will involve a BC break to our (advanced) API, so I'd like to wait for the ReactPHP component to become more stable for updating this library.

**Comment by WyriHaximus** [comment]
Are you planning to keep the external API the same?

**Comment by clue** [comment]
There are currently no plans to change anything about the API except for what *needs* to be changed, specifically this will mostly involve some minor changes to the namespaces of referenced classes.

**Comment by WyriHaximus** [comment]
Cool so targeting `^2.0 || ^1.0` should be fully compatible :tada:

**Comment by mdrost** [comment]
I would love to see some interfaces so I can create for example throttling proxy.

**Comment by nick4fake** [comment]
@clue, I am not sure about lower bound of package version. While at least, Socket v0.7 should be used due to SocketClient, I've set it to 0.8 as I only tested it agains latest components + I am not sure about lower bounds for other packages

**Comment by clue** [comment]
Small progress update: I've just release the intermediary v1.2.0 which now supports react/http v0.5 without causing a BC break :tada: While this doesn't fix this issue completely, this should relax this situation significantly.

I'll release a v1.3.0 shortly which requires this minimum version so we can update the Stream component to v0.6 at least.

The major bump to newest components has to be postponed to the v2.0.0 release because we currently expose a legacy `React\SocketClient\ConnectorInterface` on our API, which means we have a direct dependency on the deprecated react/socket-client, which does only support react/stream < v0.7.

**Comment by clue** [comment]
> I'll release a v1.3.0 shortly which requires this minimum version so we can update the Stream component to v0.6 at least.

The v1.3.0 release is now out :shipit:

**Comment by clue** [comment]
I've just released another intermediary v1.4.0 release in order to ease passing an instance of `ConnectorInterface` directly to the `Browser` so that the legacy `Sender` is now marked as deprecated. This will allow us to drop the `Sender` and its outdated dependencies in a future version so that we can support all the latest versions again :shipit:
