### ISSUE TITLE
"streaming" option is named differently from guzzle's "stream"

### ISSUE THREAD

**Issue by nick4fake** [clue/php-buzz-react#63]
Subj, these options have different names.

**Comment by clue** [comment]
Thanks for spotting! In fact this project has never claimed (or aimed) to provide compatibility with Guzzle, but if it only boils down to a simple naming issue, than I'm more than happy to look into this :+1: 

Can you provide a short gist of this and/or file a PR so we can discuss how relevant this is and if a BC break is needed and/or warranted? Thanks!

**Comment by nick4fake** [comment]
@clue sure, I'll create MR as example as soon as I have some time

**Comment by clue** [comment]
I'm closing this for now as it hasn't received any input in a while and I have no plans to change this myself anytime soon (BC break). Please come back if you feel this is still an issue and we can reopen this :+1:
