### ISSUE TITLE
Initial request data is lost when streaming response

### ISSUE THREAD

**Issue by nick4fake** [clue/php-buzz-react#64]
Hi,

In react HttpClient when response is parsed "data" event is immediately triggered after response is created. As a result, if promise that is waiting for response is issued in the next tick, data is lost (as no one handled that part of body after headers).

Simpliest solution would be wrapping response body with paused buffering stream.

**Comment by clue** [comment]
Hi @nick4fake! I'm not sure I follow what you're trying to do and what your issue is, as it's a bit unclear what you're trying to achieve from the description you've posted.

May I ask you provide a simple gist of what you're trying to achieve? Thanks!

**Comment by nick4fake** [comment]
@clue hey, thank you for a quick answer. I am not sure it is trivial to provide as gist now, so here is a little bit more:

In \React\HttpClient\Request::handleData there is direct call to stream-> emit with all the data left after headers. The problem is that there could be no data listener on the stream at that moment, if "streaming" options is enabled.

**Comment by clue** [comment]
> The problem is that there could be no data listener on the stream at that moment, if "streaming" options is enabled.

Indeed, this is by design: If streaming mode is enabled, the consumer is responsible for attaching a `data` listener. I agree that we may want to add some additional documentation here or am I missing something and you see a case where this library discards a `data` event?

**Comment by nick4fake** [comment]
@clue Sure. But what I say is that initial data event is triggered in the same loop tick too early, so that there is no chance for developer to attach a listener in the promise resolver.

I'll try to make a gist later.

**Comment by clue** [comment]
Ping @nick4fake, what is the status here?

I've been using this project in production for years and I'm currently not aware of any such issues, so any input is much appreciated :+1:

**Comment by clue** [comment]
Closing this due to a lack of feedback, as we can not reproduce this. Please come back with more details if this problem persists and we can reopen this :+1:
