### ISSUE TITLE
Custom headers not re-used when following redirect

### ISSUE THREAD

**Issue by holtkamp** [clue/php-buzz-react#88]
By default the Browser object follows HTTP redirect codes. 

However, it seems that when doing so, any custom headers that were used on the initial request are not re-used when following the redirect. Not sure whether this should be default HTTP behaviour (but I think so?)

I suppose re-using the headers should be done here https://github.com/clue/php-buzz-react/blob/ba4eb355e9ffe4bb2a9071ccc69698d48da548dc/src/Io/Transaction.php#L136

Not sure, but maybe something like: 

```php
$request = $this->messageFactory->request($method, $location, $request->getHeaders());
```

The reason how I found out: we use custom headers to simulate the "Google Bot" by using a UserAgent header like `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`

After a redirect, the default UserAgent seems to be used: `React/alpha` defined at https://github.com/reactphp/http-client/blob/d779a3b3c91ee19742839df7395b366da4471d12/src/RequestData.php#L29

**Comment by clue** [comment]
Good catch and thanks for reporting! I agree that this should probably be the default behavior. Do you feel like filing a PR for this? :shipit: :+1:

**Comment by holtkamp** [comment]
>Do you feel like filing a PR for this?

Sure! 

Do you agree with the suggested approach?

```php
$request = $this->messageFactory->request($method, $location, $request->getHeaders());
```

Or am I missing some details...?

**Comment by clue** [comment]
Sounds like a sane approach, but I'd like to see some tests for this before laying down on this :+1:

**Comment by holtkamp** [comment]
ok, can give it a try, but might take some time. Spare time seems scarce lately 😓
